### ISSUE TITLE
Node & Sails

### ISSUE THREAD

**Issue by nickmjones** [codeforgso/lightning-talks#5]
Covers Node.js basics, but concentrates on Sails—an MVC framework that lives on top of Node which offers functionality similar to Rails but with the added benefits of sockets. But with a terrible implementation of controllers.

I nominate @jdcauley :)

**Comment by jdcauley** [comment]
yeah sure.

You'll have to tell me why the controllers are terrible though.

**Comment by braidn** [comment]
Because they are written in JS?

**Comment by jdcauley** [comment]
@braidn you had the option to tell me to learn rails, but you didn't and so that response is invalid

**Comment by braidn** [comment]
I will assume you meant Ruby

**Comment by jdcauley** [comment]
Please remove my assignment
