### ISSUE TITLE
Git Team Workflow

### ISSUE THREAD

**Issue by sommanita** [codeforgso/lightning-talks#6]
Best practices for branches - which to create, which to use, which to merge, when to merge, how to merge, etc. - successful version control.

**Comment by jdcauley** [comment]
@braidn?

**Comment by braidn** [comment]
This is labeled talk idea though. Not sure what everyone is looking for BUT, my two cents:

1. Whenever or whatever code that is done should be done on a separate branch that isn't master.
1. Get as little code into a commit as possible and get the branch and a new PR on GitHub as fast as possible
1. Bring others into collaborate or just thymbs up the idea overall, start the conversation early
1. When everyone who needs to be happy is, merge

**Comment by jdcauley** [comment]
I'll take this talk @sommanita and will incorporate some of @braidn's thoughts

**Comment by jdcauley** [comment]
please remove my assignment
